# Generated by Django 3.2.1 on 2021-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', null=True)),
                ('question_type', models.CharField(choices=[('Single Selection', 'Single Selection'), ('Multi Selection', 'Multi Selection'), ('Essay', 'Essay')], max_length=20)),
                ('number_of_selection', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20)),
                ('answer_1', models.TextField(default='', null=True)),
                ('answer_1_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('answer_2', models.TextField(blank=True, default='', null=True)),
                ('answer_2_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('answer_3', models.TextField(blank=True, default='', null=True)),
                ('answer_3_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('answer_4', models.TextField(blank=True, default='', null=True)),
                ('answer_4_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('answer_5', models.TextField(blank=True, default='', null=True)),
                ('answer_5_value', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate_surname', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('creator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_first_opened', models.DateTimeField(blank=True, null=True)),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
                ('completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('answers', models.JSONField()),
                ('questions_selected', models.ManyToManyField(blank=True, null=True, to='assessment.Question')),
            ],
        ),
    ]
