# Generated by Django 3.2.1 on 2021-05-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
