# Generated by Django 3.2.1 on 2021-05-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
