# Generated by Django 3.2.1 on 2021-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_5',
            field=models.TextField(default='', null=True),
        ),
    ]
