# Generated by Django 3.2.1 on 2021-05-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
