# Generated by Django 3.2.1 on 2021-05-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20210505_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_selection',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Single Selection', 'Single Selection'), ('Multi Selection', 'Multi Selection'), ('Essay', 'Essay')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
