# Generated by Django 3.2.1 on 2021-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_assessment_assessment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='test_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='completed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
