# Generated by Django 3.2.1 on 2021-05-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20210505_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1_value',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2_value',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3_value',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4_value',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate_surname', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('creator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_first_opened', models.DateTimeField(blank=True, null=True)),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
                ('completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('answers', models.JSONField()),
                ('questions_selected', models.ManyToManyField(blank=True, null=True, to='assessment.Question')),
            ],
        ),
    ]
