# Generated by Django 3.2.1 on 2021-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_assessment_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.CharField(default='answer1', max_length=20),
            preserve_default=False,
        ),
    ]
