# Generated by Django 3.2.1 on 2021-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='time_to_complete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
