# Generated by Django 3.2.1 on 2021-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_question_number_of_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='practice_question',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
