# Generated by Django 4.0 on 2023-06-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('director', 'director'), ('candidate', 'candidate')], max_length=20, null=True),
        ),
    ]
